#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-todo-sample-frontend"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

# Firebase環境変数（Cloudflare Pagesでの本番環境用）
# これらの値はCloudflare ダッシュボードの環境変数で設定する
# 例: VITE_FIREBASE_API_KEY, VITE_FIREBASE_AUTH_DOMAIN, etc.

# Cloudflare Pages configuration
[env.production]
name = "cloudflare-todo-sample-frontend"
# Production environment variables will be set in Cloudflare Dashboard
# - VITE_FIREBASE_API_KEY
# - VITE_FIREBASE_AUTH_DOMAIN  
# - VITE_FIREBASE_PROJECT_ID
# - VITE_FIREBASE_STORAGE_BUCKET
# - VITE_FIREBASE_MESSAGING_SENDER_ID
# - VITE_FIREBASE_APP_ID

[env.staging]
name = "cloudflare-todo-sample-frontend-staging"
# Staging environment variables will be set in Cloudflare Dashboard
# Same variables as production but pointing to staging Firebase project